# Importing necessary Libraries

In [1]:
import numpy as np
import pandas as pd
from grad_boost import GradientBooster
from sklearn.ensemble import HistGradientBoostingRegressor
from dataset import *
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from error_define import downside_square_error

# Loading Dataset

In [12]:
X,y = load_dataset_features()
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42) 

In [13]:
X.head()

PM2.5 (µg/m³)  PM10 (µg/m³)  NO (µg/m³)  NO2 (µg/m³)  NOx (ppb)  \
0          46.00         80.00        1.29         9.16      12.02   
1          46.00         80.00        1.74         8.93      12.48   
2          45.62         79.92        1.87         8.56      12.17   
3          41.00         72.92        1.83         8.72      12.37   
4          41.00         79.00        1.69         7.91      11.30   

   NH3 (µg/m³)  SO2 (µg/m³)  CO (mg/m³)  Ozone (µg/m³)  AQI_calculated  \
0        27.19        13.56        0.40          15.80            67.0   
1        30.29        13.71        0.41          15.52            68.0   
2        28.20        13.88        0.41          15.33            68.0   
3        26.69        13.77        0.40          15.30            68.0   
4        26.83        13.87        0.41          15.49            68.0   

   Station_IITG   Station_LGBI Airport   Station_Pan Bazaar   \
0            0.0                    0.0                  0.0   
1            0.0                    0.0                  0.0   
2            0.0                    0.0                  0.0   
3            0.0                    0.0                  0.0   
4            0.0                    0.0                  0.0   

   Station_Railway Colony   year  month  dayofweek  
0                      1.0  2019      2          6  
1                      1.0  2019      2          6  
2                      1.0  2019      2          6  
3                      1.0  2019      2          6  
4                      1.0  2019      2          6

In [14]:
y_train = np.array(y_train).reshape(X_train.shape[0],1)
y_test = np.array(y_test).reshape(X_test.shape[0],1)

# Training the model and evaluating

In [ ]:
g = GradientBooster()
losses = g.train(X_train,y_train)

In [ ]:
pred = g.predict(X_test)
mean_squared_error(pred,y_test)

5000.6376210013705

In [ ]:
downside_square_error(pred,y_test)

array([2956.14375475])

In [ ]:
model = HistGradientBoostingRegressor(max_depth=10, min_samples_leaf=5,learning_rate=0.1,max_iter=4000)
model.fit(X_train,y_train)

In [ ]:
mean_squared_error(model.predict(X_test),y_test)

453.2006995027215

In [ ]:
downside_square_error(model.predict(X_test),y_test)

array([249.23985466])

# Training on dataset with features

In [ ]:
X,y = load_dataset_features()

In [ ]:
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42) 

In [ ]:
y_train = np.array(y_train).reshape(X_train.shape[0],1)
y_test = np.array(y_test).reshape(X_test.shape[0],1)

In [ ]:
g = GradientBooster()
losses = g.train(X_train,y_train)

In [ ]:
pred = g.predict(X_test)
mean_squared_error(pred,y_test)

1893.567037959232

In [15]:
model = HistGradientBoostingRegressor(max_depth=10, min_samples_leaf=5,learning_rate=0.1,max_iter=4000)
model.fit(X_train,y_train)

d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


HistGradientBoostingRegressor(max_depth=10, max_iter=4000, min_samples_leaf=5)

In [16]:
mean_squared_error(model.predict(X_test),y_test)

453.2006995027215

In [17]:
downside_square_error(model.predict(X_test),y_test)

array([249.23985466])